echo "Setting Env Variables"
set SERVER_IP=IP:HOST
set QUOTA=4
set FTP_IP=IP
set FTP_USER=XXX
set FTP_PASSWORD=XXX
set FTP_BASEDIR=path/there
set EMAIL_TEMPLATE={}
set MAIL_PASSWORD=XXXXX
set MAIL_USERNAME=XXXX
set MAIL_SERVER=somewhere.com
set DISCORD_URL=https://XXXX
set CLUB_NAME=My Club
set ACCESS_CODE=XXXXX
set CODE_SALT=XXXXXXX
set WHITELIST_FILE=whitelist.json
set ADMIN_EMAIL=admin@host.com
set ADMIN_NAME=Mr Admin
set FLASK_APP=MinerClub:app
